spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: saptarshi.dev.test@gmail.com
    password: jsjy vvhf qtko uvls
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
